name: run main.py

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à 00:00 AM
  workflow_dispatch: # permet de déclencher manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # vérifier le contenu du dépôt pour le runner GitHub

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # installer la version de Python nécessaire
          
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      #- name: install python packages
        #run: |
          #python -m pip install --upgrade pip
          #pip install -r requirements.txt
          
      - name: execute py script # exécuter main.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python main.py
